import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import joblib

# Note: heading columns are NOT included here directly. 0-360 degree
# headings are "circular" -- 359 deg and 1 deg are almost the same
# direction, but as plain numbers they look as far apart as possible.
# Instead, we convert each heading into two features: sin(heading) and
# cos(heading). Together, a (sin, cos) pair uniquely represents an angle,
# and crucially, 359 deg and 1 deg now end up with very similar sin/cos
# values -- which is what actually reflects reality, so the model can
# learn the relationship correctly.
FEATURE_COLS = ["altitude", "drone_speed", "drone_heading_sin", "drone_heading_cos",
                 "wind_speed", "wind_heading_sin", "wind_heading_cos"]
TARGET_COLS = ["drift_east", "drift_north"]


def add_heading_features(df):
    """
    Takes a DataFrame that has raw 'drone_heading' / 'wind_heading' degree
    columns, and adds the sin/cos versions used as actual model inputs.
    Kept as a separate function so both training and prediction use the
    exact same transformation (important -- they must always match).
    """
    df = df.copy()
    df["drone_heading_sin"] = np.sin(np.radians(df["drone_heading"]))
    df["drone_heading_cos"] = np.cos(np.radians(df["drone_heading"]))
    df["wind_heading_sin"] = np.sin(np.radians(df["wind_heading"]))
    df["wind_heading_cos"] = np.cos(np.radians(df["wind_heading"]))
    return df


def train_model(csv_path="ballistic_dataset.csv", model_path="landing_model.pkl"):
    # Load the dataset generated by ballistic_physics.py
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} rows from {csv_path}")

    df = add_heading_features(df)  # add the sin/cos columns

    X = df[FEATURE_COLS]   # inputs: altitude, drone_speed, heading (as sin/cos), wind_speed, wind heading (as sin/cos)
    y = df[TARGET_COLS]    # outputs: drift_east, drift_north (predicted together, RandomForest
                            # supports multiple output columns natively, no extra setup needed)

    # Split into training data (used to fit the model) and test data (held
    # back, used only to check how well the model generalizes to examples
    # it has NOT seen). 80/20 is a common default split.
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42)

    # n_estimators=200 -- the forest is made of 200 individual decision
    # trees, and the final prediction is their average. More trees = more
    # stable predictions, but slower to train. 200 is a reasonable default.
    model = RandomForestRegressor(n_estimators=200, random_state=42)
    model.fit(X_train, y_train)

    # Evaluate: MAE (Mean Absolute Error) = on average, how many meters off
    # is the model's prediction, compared to the true drift value.
    y_pred = model.predict(X_test)
    mae_east = mean_absolute_error(y_test["drift_east"], y_pred[:, 0])
    mae_north = mean_absolute_error(y_test["drift_north"], y_pred[:, 1])

    print(f"MAE on test set -- East: {mae_east:.3f} m, North: {mae_north:.3f} m")

    joblib.dump(model, model_path)
    print(f"Model saved to {model_path}")
    return model


def predict_drift_ml(model, altitude, drone_speed, drone_heading_deg, wind_speed, wind_heading_deg):
    """
    Same input/output shape as physics.predict_drift(), but using the
    trained ML model instead of the hand-written formula. Useful later for
    comparing "what physics says" vs "what the ML model says" side by side.
    """
    row = pd.DataFrame([{
        "altitude": altitude,
        "drone_speed": drone_speed,
        "drone_heading": drone_heading_deg,
        "wind_speed": wind_speed,
        "wind_heading": wind_heading_deg,
    }])
    row = add_heading_features(row)  # same transformation used during training
    pred = model.predict(row[FEATURE_COLS])[0]
    return pred[0], pred[1]  # drift_east, drift_north


if __name__ == "__main__":
    model = train_model()

    # Sanity check: compare ML prediction to the same example we tested
    # the physics formula on earlier (20m altitude, 5m/s East, 3m/s wind
    # from South -- physics gave 10.10m East, 6.06m North).
    drift = predict_drift_ml(model, altitude=20, drone_speed=5,
                              drone_heading_deg=90, wind_speed=3, wind_heading_deg=0)
    print(f"ML prediction for the same example: "
          f"{drift[0]:.2f}m East, {drift[1]:.2f}m North")